In [6]:
import pandas as pd

In [7]:
df = pd.read_csv('./passengers.csv', sep='\t')
df.head()

     Фамилия       Имя      Отчество Дата рождения Серия и номер паспорта
0   Брынских     Ефрем    Германович    23.01.1966            4896 754042
1  Черкашина      Юлия     Игнатевна    20.04.1970            4979 362305
2  Бельтюков   Алексей    Викторович    15.03.1977            4078 109679
3   Симонова  Василиса      Артемова    11.07.1978            4743 754379
4     Купцов     Игнат  Валентинович    07.07.1966            4715 756686

In [8]:
for index, row in df.iterrows():
    last_name, name, patron, date, passport = row
    date = date.split('.')
    a = "'"
    print(f"insert into project.passengers values ({index + 1100}, {a+name+a}, {a+last_name+a}, {a+patron+a}, {a+'-'.join(date[::-1])+a}, {a+str(passport)+a});")

insert into project.passengers values (1100, 'Ефрем', 'Брынских', 'Германович', '1966-01-23', '4896 754042');
insert into project.passengers values (1101, 'Юлия', 'Черкашина', 'Игнатевна', '1970-04-20', '4979 362305');
insert into project.passengers values (1102, 'Алексей', 'Бельтюков', 'Викторович', '1977-03-15', '4078 109679');
insert into project.passengers values (1103, 'Василиса', 'Симонова', 'Артемова', '1978-07-11', '4743 754379');
insert into project.passengers values (1104, 'Игнат', 'Купцов', 'Валентинович', '1966-07-07', '4715 756686');
insert into project.passengers values (1105, 'Ольга', 'Лукашенко', 'Никитьевна', '1976-10-26', '4369 821078');
insert into project.passengers values (1106, 'Савва', 'Яндашевский', 'Иванович', '1994-01-23', '4426 214275');
insert into project.passengers values (1107, 'Марфа', 'Абрашина', 'Игнатьевна', '1977-10-15', '4699 362114');
insert into project.passengers values (1108, 'Валерия', 'Кулумбаева', 'Витальевна', '1973-04-07', '4585 130698');
insert into project.passengers values (1109, 'Виктория', 'Загидуллина', 'Макаровна', '1991-03-04', '4236 401238');
insert into project.passengers values (1110, 'Лидия', 'Жирова', 'Наумовна', '1992-12-03', '4870 363280');
insert into project.passengers values (1111, 'Кирилл', 'Бунин', 'Гаврннлович', '1994-08-12', '4877 907372');
insert into project.passengers values (1112, 'Зинаида', 'Мананникова', 'Константиновна', '1989-12-08', '4754 106294');
insert into project.passengers values (1113, 'Степан', 'Савинков', 'Яковеевичевич', '1990-08-15', '4944 160756');
insert into project.passengers values (1114, 'Денис', 'Бобров', 'Филиппович', '1979-09-18', '4984 831345');
insert into project.passengers values (1115, 'Нина', 'Муравьёва', 'Николаевна', '1979-06-03', '4329 435459');
insert into project.passengers values (1116, 'Геннадий', 'Андроников', 'Прохорович', '1965-05-24', '4579 698843');
insert into project.passengers values (1117, 'Антон', 'Седельников', 'Юлианович', '1961-06-03', '4088 288683');
insert into project.passengers values (1118, 'Маргарита', 'Ивазова', 'Евгеньевна', '1976-04-08', '4110 925812');
insert into project.passengers values (1119, 'Серафима', 'Чана', 'Юлиановна', '1990-09-26', '4547 472863');
insert into project.passengers values (1120, 'Вера', 'Васильевых', 'Климентьевна', '1966-06-10', '4052 800800');
insert into project.passengers values (1121, 'Савва', 'Ястребов', 'Сергеевич', '1989-09-18', '4733 813024');
insert into project.passengers values (1122, 'Кузьма', 'Кочинян', 'Афанасьевич', '1976-12-28', '4573 865797');
insert into project.passengers values (1123, 'Анжела', 'Печеникова', 'Никандровна', '1966-11-21', '4744 679516');
insert into project.passengers values (1124, 'Вениамин', 'Эфиров', 'Викторович', '1970-07-09', '4837 526601');
insert into project.passengers values (1125, 'Ефим', 'Фернандес', 'Климентьевич', '1966-06-17', '4316 616768');
insert into project.passengers values (1126, 'Арина', 'Бутылина', 'Семеновна', '1972-01-20', '4354 868684');
insert into project.passengers values (1127, 'Григорий', 'Корявин', 'Яковлевич', '1988-11-18', '4895 405418');
insert into project.passengers values (1128, 'Петр', 'Элефтеров', 'Викторович', '1968-04-12', '4851 849498');
insert into project.passengers values (1129, 'Гавриил', 'Яковцов', 'Маркович', '1988-02-07', '4126 605460');
insert into project.passengers values (1130, 'Захар', 'Блатов', 'Лукьевич', '1988-11-17', '4021 809829');
insert into project.passengers values (1131, 'Валентина', 'Ерхова', 'Александровна', '1964-07-16', '4832 681469');
insert into project.passengers values (1132, 'Вячеслав', 'Тимашёв', 'Макарович', '1961-12-19', '4243 470468');
insert into project.passengers values (1133, 'Ирина', 'Абдулова', 'Григорьевна', '1981-09-12', '4446 625038');
insert into project.passengers values (1134, 'Аполлинария', 'Руднева', 'Евгеньевна', '1994-07-16', '4325 205384');
insert into project.passengers values (1135, 'Михаил', 'Изотов', 'Макарович', '1987-10-08', '4350 748762');
insert into project.passengers values (1136, 'Ася', 'Боркова', 'Иннокентьевна', '1996-04-01', '4719 622543');
insert into project.passengers values (1137, 'Людмила', 'Кабальнова', 'Якововна', '1981-02-22', '4549 532821');
insert into project.passengers values (1138, 'Юрий', 'Шидловский', 'Викторович', '1988-07-11', '4818 118180');
insert into project.passengers values (1139, 'Игнат', 'Рябец', 'Севастьянович', '1995-10-04', '4075 707642');
insert into project.passengers values (1140, 'Герман', 'Кондаков', 'Данилович', '1983-01-24', '4243 609589');
insert into project.passengers values (1141, 'Кирилл', 'Талалихин', 'Лукьевич', '1983-03-24', '4812 159387');
insert into project.passengers values (1142, 'Надежда', 'Евстигнеева', 'Максимовна', '1971-07-10', '4136 738341');
insert into project.passengers values (1143, 'Серафима', 'Витаева', 'Саввановна', '1993-01-13', '4569 706535');
insert into project.passengers values (1144, 'Аркадий', 'Яковкин', 'Сергеевич', '1964-07-14', '4386 574290');
insert into project.passengers values (1145, 'Степан', 'Ромазан', 'Прокльев', '1969-08-03', '4822 206996');
insert into project.passengers values (1146, 'Захар', 'Иньшов', 'Максимович', '1978-04-25', '4484 165636');
insert into project.passengers values (1147, 'Иван', 'Константинов', 'Александрович', '1992-01-01', '4628 444254');
insert into project.passengers values (1148, 'Анна', 'Солодская', 'Леонтьевна', '1982-08-19', '4279 515389');
insert into project.passengers values (1149, 'Клавдия', 'Проничева', 'Афанасьевна', '1968-07-26', '4675 852498');
insert into project.passengers values (1150, 'Пелагея', 'Ярошенко', 'Вениаминовна', '1976-05-18', '4423 763726');
insert into project.passengers values (1151, 'Раиса', 'Чана', 'Федоровна', '1961-01-26', '4256 815078');
insert into project.passengers values (1152, 'Алена', 'Печкина', 'Петровна', '1991-10-13', '4523 645525');
insert into project.passengers values (1153, 'Ольга', 'Шведова', 'Феодосьевна', '1981-12-12', '4852 252847');
insert into project.passengers values (1154, 'Игнат', 'Серых', 'Германович', '1983-11-27', '4369 654342');
insert into project.passengers values (1155, 'Филипп', 'Любов', 'Панкратович', '1968-02-06', '4683 351644');
insert into project.passengers values (1156, 'Антон', 'Пондяков', 'Петрович', '1995-05-19', '4548 626122');
insert into project.passengers values (1157, 'Алина', 'Карбаинова', 'Панкратовна', '1980-06-22', '4455 167852');
insert into project.passengers values (1158, 'Леонид', 'Яимов', 'Тимофеевич', '1974-01-21', '4326 282073');
insert into project.passengers values (1159, 'Афанасия', 'Гурьянова', 'Георгьевна', '1966-10-16', '4970 170508');
insert into project.passengers values (1160, 'Марина', 'Ямбушева', 'Николаевна', '1977-11-05', '4434 876556');
insert into project.passengers values (1161, 'Ефрем', 'Гришкин', 'Панкратович', '1976-09-09', '4139 150815');
insert into project.passengers values (1162, 'Василий', 'Шалимов', 'Давидович', '1986-05-24', '4262 621391');
insert into project.passengers values (1163, 'Катерина', 'Суслова', 'Семеновна', '1967-06-14', '4468 275329');
insert into project.passengers values (1164, 'Валерия', 'Никанорова', 'Григорьевна', '1987-04-03', '4670 403400');
insert into project.passengers values (1165, 'Любовь', 'Кобонова', 'Макаровна', '1972-01-03', '4222 470632');
insert into project.passengers values (1166, 'Светлана', 'Шипицина', 'Тимофеевна', '1986-08-11', '4131 805747');
insert into project.passengers values (1167, 'Вера', 'Котяша', 'Давидовна', '1962-04-18', '4353 321961');
insert into project.passengers values (1168, 'Алексей', 'Дудинов', 'Тимофеевич', '1968-08-11', '4316 413407');
insert into project.passengers values (1169, 'Егор', 'Пузаков', 'Филиппович', '1989-04-10', '4525 653104');
insert into project.passengers values (1170, 'Федор', 'Кузькин', 'Константинович', '1972-02-28', '4322 676624');
insert into project.passengers values (1171, 'Анфиса', 'Ясевича', 'Прохор', '1974-08-19', '4224 833643');
insert into project.passengers values (1172, 'Серафима', 'Мирсиянова', 'Ефимовна', '1968-02-14', '4997 560575');
insert into project.passengers values (1173, 'Ева', 'Таушева', 'Прохоровна', '1986-12-05', '4681 874446');
insert into project.passengers values (1174, 'Антонина', 'Дорохова', 'Васильевна', '1990-08-25', '4078 305794');
insert into project.passengers values (1175, 'Ульяна', 'Жидкова', 'Данииловна', '1984-12-25', '4037 393919');
insert into project.passengers values (1176, 'Ирина', 'Яшенкина', 'Денисовна', '1962-08-26', '4264 716208');
insert into project.passengers values (1177, 'Давид', 'Ячевский', 'Дмитриевич', '1972-11-26', '4881 693935');
insert into project.passengers values (1178, 'Валерий', 'Лившиц', 'Евгеньевич', '1983-02-03', '4345 827105');
insert into project.passengers values (1179, 'Вероника', 'Кочкорбаева', 'Прокловна', '1986-01-24', '4172 477094');
insert into project.passengers values (1180, 'Алла', 'Зыкова', 'Адамовна', '1982-05-03', '4819 819751');
insert into project.passengers values (1181, 'Татьяна', 'Максимова', 'Макаровна', '1974-05-26', '4798 871933');
insert into project.passengers values (1182, 'Роман', 'Ященко', 'Прохорович', '1976-12-05', '4829 418488');
insert into project.passengers values (1183, 'Кирилл', 'Летов', 'Сергеевич', '1982-03-03', '4583 544770');
insert into project.passengers values (1184, 'Валерий', 'Механтьев', 'Кириллович', '1992-02-14', '4914 298160');
insert into project.passengers values (1185, 'Любовь', 'Набиуллина', 'Серафимовна', '1967-10-11', '4476 365261');
insert into project.passengers values (1186, 'Савва', 'Бугаев', 'Саввеевич', '1961-10-10', '4962 819762');
insert into project.passengers values (1187, 'Афанасий', 'Мигунов', 'Германович', '1971-06-05', '4352 707069');
insert into project.passengers values (1188, 'Роман', 'Кукушкин', 'Леонидович', '1989-04-15', '4513 828159');
insert into project.passengers values (1189, 'Аполлинария', 'Куклина', 'Степановна', '1977-09-13', '4427 143177');
insert into project.passengers values (1190, 'Яков', 'Цуцких', 'Антонович', '1967-09-21', '4993 795328');
insert into project.passengers values (1191, 'Лев', 'Колобков', 'Кириллович', '1965-01-19', '4449 897982');
insert into project.passengers values (1192, 'Афанасий', 'Винокуров', 'Феоктистович', '1977-01-27', '4821 348697');
insert into project.passengers values (1193, 'Василиса', 'Маринина', 'Ивановна', '1983-07-10', '4327 392910');
insert into project.passengers values (1194, 'Захар', 'Кумовьев', 'Даниилович', '1981-02-14', '4585 799319');
insert into project.passengers values (1195, 'Зоя', 'Быстрова', 'Романовна', '1980-05-23', '4228 593211');
insert into project.passengers values (1196, 'Анастасия', 'Зубарева', 'Аркадьевна', '1971-04-17', '4834 910253');
insert into project.passengers values (1197, 'Юлиана', 'Соболева', 'Порфнрьевна', '1980-11-27', '4121 703433');
insert into project.passengers values (1198, 'Александра', 'Терехова', 'Феоктистовна', '1995-10-12', '4113 244005');
insert into project.passengers values (1199, 'Степан', 'Каретников', 'Феоктистович', '1995-12-13', '4437 718209');
insert into project.passengers values (1200, 'Рада', 'Эзрина', 'Степановна', '1996-01-22', '4519 876777');
insert into project.passengers values (1201, 'Карина', 'Ревякина', 'Лаврентьевна', '1975-01-11', '4247 574566');
insert into project.passengers values (1202, 'Алиса', 'Смирновская', 'Захаровна', '1980-01-04', '4858 582655');
insert into project.passengers values (1203, 'Ульяна', 'Игнатенкова', 'Антоновна', '1984-03-07', '4059 790897');
insert into project.passengers values (1204, 'Адам', 'Немцев', 'Арсеньевич', '1965-02-18', '4131 734163');
insert into project.passengers values (1205, 'Денис', 'Куклачёв', 'Максимович', '1995-08-20', '4189 945357');
insert into project.passengers values (1206, 'Валерия', 'Абалихина', 'Ипполитовна', '1994-02-17', '4651 570093');
insert into project.passengers values (1207, 'Евгений', 'Валевач', 'Валерьевич', '1990-07-01', '4395 252272');
insert into project.passengers values (1208, 'Тимофей', 'Марков', 'Ильич', '1990-10-10', '4944 842261');
insert into project.passengers values (1209, 'Валерий', 'Беляков', 'Антонрвич', '1962-07-07', '4189 525962');
insert into project.passengers values (1210, 'Анна', 'Шульц', 'Феодосьевна', '1973-11-28', '4440 467888');
insert into project.passengers values (1211, 'Кирилл', 'Ловзанский', 'Михаилович', '1965-04-28', '4173 472418');
insert into project.passengers values (1212, 'Пелагея', 'Тукай', 'Юлиановна', '1964-10-11', '4115 382921');
insert into project.passengers values (1213, 'Евгения', 'Свалова', 'Витальевна', '1995-04-16', '4379 866754');
insert into project.passengers values (1214, 'Дарья', 'Каткова', 'Наумовна', '1986-02-12', '4385 951155');
insert into project.passengers values (1215, 'Севастьян', 'Ермишин', 'Георгиевич', '1961-08-11', '4722 989872');
insert into project.passengers values (1216, 'Федор', 'Холопов', 'Юрьевич', '1982-10-14', '4322 420844');
insert into project.passengers values (1217, 'Тимофей', 'Бабанов', 'Прохорович', '1983-07-19', '4324 473518');
insert into project.passengers values (1218, 'Серафима', 'Делова', 'Леонидовна', '1979-07-20', '4693 279545');
insert into project.passengers values (1219, 'Артем', 'Рябец', 'Валентинович', '1961-12-17', '4284 723648');
insert into project.passengers values (1220, 'Лаврентий', 'Изотов', 'Власович', '1980-04-17', '4081 187300');
insert into project.passengers values (1221, 'Ксения', 'Казанец', 'Севастьяновна', '1967-09-14', '4560 687182');
insert into project.passengers values (1222, 'Таисия', 'Ибрагимова', 'Филипповна', '1995-02-22', '4976 610822');
insert into project.passengers values (1223, 'Лидия', 'Котенко', 'Давидович', '1974-01-03', '4870 896558');
insert into project.passengers values (1224, 'Карина', 'Битнера', 'Валерьевна', '1982-11-27', '4163 257768');
insert into project.passengers values (1225, 'Галина', 'Помелова', 'Никандровна', '1994-01-26', '4639 578063');
insert into project.passengers values (1226, 'Арсений', 'Мятлев', 'Валентинович', '1960-09-06', '4753 135831');
insert into project.passengers values (1227, 'Василий', 'Мамыкин', 'Семенович', '1992-04-14', '4382 221092');
insert into project.passengers values (1228, 'Феликс', 'Чуринов', 'Акимович', '1968-09-01', '4749 415926');
insert into project.passengers values (1229, 'Анастасия', 'Ященко', 'Ильиновна', '1993-08-04', '4134 508602');
insert into project.passengers values (1230, 'Ева', 'Угличинина', 'Прохоровна', '1963-05-23', '4045 953244');
insert into project.passengers values (1231, 'Анжела', 'Хлебова', 'Никифоровна', '1966-07-21', '4024 742667');
insert into project.passengers values (1232, 'Арсений', 'Борхес', 'Прокопьевич', '1977-01-15', '4079 911497');
insert into project.passengers values (1233, 'Клара', 'Верица', 'Антоновна', '1962-04-18', '4884 722792');
insert into project.passengers values (1234, 'Максим', 'Янин', 'Кириллович', '1993-10-19', '4589 388852');
insert into project.passengers values (1235, 'Герман', 'Щербаков', 'Власович', '1965-12-18', '4936 143266');
insert into project.passengers values (1236, 'Макар', 'Чемерис', 'Васильевич', '1986-07-25', '4378 470055');
insert into project.passengers values (1237, 'Валентин', 'Пережогин', 'Никифорович', '1993-12-12', '4429 405448');
insert into project.passengers values (1238, 'Георгий', 'Лисицын', 'Тимофеевич', '1982-11-08', '4920 419471');
insert into project.passengers values (1239, 'Людмила', 'Эфирова', 'Игнатевна', '1976-02-26', '4180 575054');
insert into project.passengers values (1240, 'Леонтий', 'Дубков', 'Ефимович', '1993-11-01', '4020 580778');
insert into project.passengers values (1241, 'Егор', 'Овечкин', 'Георгиевич', '1983-05-09', '4372 283907');
insert into project.passengers values (1242, 'Серафим', 'Крак', 'Ильич', '1965-09-16', '4961 707753');
insert into project.passengers values (1243, 'Феликс', 'Канунников', 'Никифорович', '1970-01-13', '4421 571156');
insert into project.passengers values (1244, 'Прохор', 'Дворников', 'Константинович', '1973-09-06', '4869 273887');
insert into project.passengers values (1245, 'Петр', 'Столяров', 'Всеволодович', '1993-06-18', '4697 194551');
insert into project.passengers values (1246, 'Никита', 'Борисов', 'Павлович', '1963-06-27', '4923 516727');
insert into project.passengers values (1247, 'Артем', 'Дагин', 'Антонович', '1973-03-20', '4398 638549');
insert into project.passengers values (1248, 'Семен', 'Щеткин', 'Трофимович', '1991-04-14', '4062 536158');
insert into project.passengers values (1249, 'Лаврентий', 'Сиянских', 'Федотович', '1976-02-03', '4360 996308');
insert into project.passengers values (1250, 'Клара', 'Эскина', 'Павловна', '1967-07-25', '4347 948586');
insert into project.passengers values (1251, 'Валерий', 'Шурупов', 'Леонидович', '1966-04-25', '4449 892862');
insert into project.passengers values (1252, 'Пелагея', 'Рудавина', 'Степановна', '1979-06-23', '4870 261552');
insert into project.passengers values (1253, 'Анастасия', 'Нусинова', 'Даниловна', '1968-01-19', '4724 744635');
insert into project.passengers values (1254, 'Нонна', 'Скрябина', 'Семеновна', '1994-07-05', '4524 656453');
insert into project.passengers values (1255, 'Никифор', 'Рогов', 'Степанович', '1994-11-08', '4473 326513');
insert into project.passengers values (1256, 'Аполлинария', 'Каблукова', 'Герасимовна', '1969-06-12', '4662 152843');
insert into project.passengers values (1257, 'Александр', 'Костюк', 'Кириллович', '1982-07-09', '4326 270387');
insert into project.passengers values (1258, 'Аркадий', 'Опринчук', 'Львович', '1986-03-01', '4556 674161');
insert into project.passengers values (1259, 'Давид', 'Царицын', 'Всеволодович', '1983-05-07', '4929 188395');
insert into project.passengers values (1260, 'Лариса', 'Котова', 'Лаврентьевна', '1960-10-24', '4857 268323');
insert into project.passengers values (1261, 'Екатерина', 'Муратова', 'Григориевна', '1990-06-24', '4239 332757');
insert into project.passengers values (1262, 'Петр', 'Михайличенко', 'Филиппович', '1984-03-09', '4861 495232');
insert into project.passengers values (1263, 'Серафима', 'Галдина', 'Ефимовна', '1984-01-02', '4580 511257');
insert into project.passengers values (1264, 'Пелагея', 'Гершельмана', 'Максимовна', '1970-01-06', '4896 963042');
insert into project.passengers values (1265, 'Анна', 'Можаева', 'Венедиктовна', '1967-10-15', '4830 405950');
insert into project.passengers values (1266, 'Гавриил', 'Хабалов', 'Валерьевич', '1966-01-20', '4296 831176');
insert into project.passengers values (1267, 'Анастасия', 'Бурдакова', 'Юрьевна', '1970-05-16', '4695 841860');
insert into project.passengers values (1268, 'Петр', 'Гусев', 'Елизарович', '1960-07-26', '4973 411399');
insert into project.passengers values (1269, 'Алла', 'Косицкая', 'Панкратовна', '1986-10-13', '4634 853388');
insert into project.passengers values (1270, 'Иван', 'Невский', 'Кириллович', '1992-11-09', '4720 224053');
insert into project.passengers values (1271, 'Григорий', 'Нырцев', 'Яковлевич', '1967-02-01', '4281 950945');
insert into project.passengers values (1272, 'Павел', 'Халипов', 'Филиппович', '1993-05-01', '4330 845329');
insert into project.passengers values (1273, 'Марьямна', 'Жиганова', 'Захаровна', '1989-06-21', '4494 546257');
insert into project.passengers values (1274, 'Валентин', 'Лагранский', 'Трофимович', '1972-08-12', '4875 333689');
insert into project.passengers values (1275, 'Валерия', 'Прокашева', 'Акимовна', '1990-06-01', '4432 844632');
insert into project.passengers values (1276, 'Анфиса', 'Ижутина', 'Степановна', '1995-10-24', '4725 485312');
insert into project.passengers values (1277, 'Иван', 'Ли', 'Евгеньевич', '1994-11-22', '4012 668285');
insert into project.passengers values (1278, 'Марфа', 'Розенбаха', 'Якововна', '1965-01-06', '4018 173060');
insert into project.passengers values (1279, 'Алина', 'Маслака', 'Наумовна', '1977-08-03', '4995 585855');

In [5]:
df.head()

     Фамилия      Имя     Отчество Дата рождения Серия и номер паспорта
0  Криштофич  Зинаида    Захаровна    21.12.1973            4137 761086
1    Куликов  Николай   Витальевич    16.09.1990            4893 753917
2   Анисимов     Марк        Ильич    11.08.1994            4822 224954
3   Иванкова     Нина     Марковна    10.06.1974            4238 721929
4    Валеева    Алена  Серафимовна    12.02.1967            4594 816487